language: go

services:
  - docker

matrix:
  include:
  - go: 1.x
    os: linux
    env: FULL=true
  - go: tip
    os: linux


install:
  - go get ./...
  - if [ "$FULL" = "true" ]; then go get golang.org/x/lint/golint; fi;
  - if [ "$FULL" = "true" ]; then go get github.com/mattn/goveralls; fi;

before_script:
  - if [ "$FULL" = "true" ]; then go vet $(go list ./... | grep -v vendor); fi;
  - if [ "$FULL" = "true" ]; then test -z "$(gofmt -s -l . 2>&1 | grep -v vendor | tee /dev/stderr)"; fi;
  - if [ "$FULL" = "true" ]; then test -z "$(golint ./... 2>&1 | tee /dev/stderr)"; fi;

script:
  - docker pull nats
  - docker run -p 4222:4222 -d nats
  - if [ "$FULL" = "true" ]; then goveralls -service=travis-ci; else go test -race $(go list ./... | grep -v /vendor/); fi;
